version: '3'
services:
  app:
    build: ./rails-booking
    command: rails s -b 0.0.0.0
    volumes:
      - ./rails-booking:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:13.3
    container_name: db
    environment:
      POSTGRES_USER: bookingUser
      POSTGRES_PASSWORD: qwerty4
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
